apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: scpro-disa-results-pipeline
  namespace: flink-jobs
spec:
  deploymentName: session-cluster
  job:
    # jarURI: https://github.com/IHMAfrica/zm-scpro-disa-results-pipeline/releases/download/latest/zm-scpro-disa-results-pipeline-all.jar
    jarURI: local:///opt/flink/zm-scpro-disa-results-pipeline-all.jar
    entryClass: zm.gov.moh.hie.scp.StreamingJob
    parallelism: 2
    upgradeMode: stateless
    state: running
    # arguments:
    #   - "--kafka.bootstrap.servers=<your-broker>"
    #   - "--kafka.topic=<your-topic>"
