apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: scpro-disa-results-pipeline
  namespace: flink-jobs
spec:
  deploymentName: session-cluster
  job:
    jarURI: JAR_HTTP_URL
    entryClass: zm.gov.moh.hie.scp.StreamingJob
    parallelism: 2
    upgradeMode: stateless
    # arguments:
    #   - "--kafka.bootstrap.servers=<your-broker>"
    #   - "--kafka.topic=<your-topic>"
